spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:n26
    username: sa
    password:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

server:
  port: 8080

retrievalTimeFrameInSeconds: 60


